Udemy_Spice_MVC/Areas/Admin/Controllers/CouponController.cs
using Microsoft.AspNetCore.Authorization;//added
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;//added
using System;
using System.Collections.Generic;
using System.IO;//added
using System.Linq;
using System.Threading.Tasks;
using Udemy_Spice_MVC.Data;//added
using Udemy_Spice_MVC.Models;//added
using Udemy_Spice_MVC.Utility;//added

namespace Udemy_Spice_MVC.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class CouponController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public Coupon couponBound { get; set; }

        public CouponController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _db.coupons.ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePOST()
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] p1 = null;
                    using (var fs1 = files[0].OpenReadStream())
                    {
                        using (var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            p1 = ms1.ToArray();
                        }
                    }
                    couponBound.picture = p1;
                }
                _db.coupons.Add(couponBound);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(couponBound);
        }

        //GET - Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var coupon = await _db.coupons.SingleOrDefaultAsync(m => m.id == id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        //GET - Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var coupon = await _db.coupons.SingleOrDefaultAsync(m => m.id == id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        //POST - Edit
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPOST()
        {
            if (couponBound.id == 0)
            {
                return NotFound();
            }

            var couponFromDb = await _db.coupons.Where(c => c.id == couponBound.id).FirstOrDefaultAsync();

            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] p1 = null;
                    using (var fs1 = files[0].OpenReadStream())
                    {
                        using (var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            p1 = ms1.ToArray();
                        }
                    }
                    couponFromDb.picture = p1;
                }
                couponFromDb.minimum_amount = couponBound.minimum_amount;
                couponFromDb.name = couponBound.name;
                couponFromDb.discount = couponBound.discount;
                couponFromDb.coupon_type = couponBound.coupon_type;
                couponFromDb.is_active = couponBound.is_active;

                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(couponBound);
        }

        //GET - Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var coupon = await _db.coupons.SingleOrDefaultAsync(m => m.id == id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        //POST - Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var couponDelete = await _db.coupons.FindAsync(id);
            if (couponDelete != null)
            {
                _db.coupons.Remove(couponDelete);
                await _db.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Udemy_Spice_MVC/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;//added
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;//added
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;//added
using System.Threading.Tasks;
using Udemy_Spice_MVC.Data;//added
using Udemy_Spice_MVC.Utility;//added

namespace Udemy_Spice_MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.ManagerUser)]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            return View(await _db.app_users.Where(u => u.Id != claim.Value).ToListAsync());
        }
        public async Task<IActionResult> Lock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _db.app_users.FirstOrDefaultAsync(m => m.Id == id);

            if (applicationUser == null)
            {
                return NotFound();
            }

            applicationUser.LockoutEnd = DateTime.Now.AddYears(1000);

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UnLock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _db.app_users.FirstOrDefaultAsync(m => m.Id == id);

            if (applicationUser == null)
            {
                return NotFound();
            }

            applicationUser.LockoutEnd = DateTime.Now;

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Udemy_Spice_MVC/Views/Shared/_CreateAndBackToListButtonPartial.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Create" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Udemy_Spice_MVC/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info">
        <i class="fas fa-plus"></i> Create New
    </a>
</p>

Udemy_Spice_MVC/Views/Shared/_DeleteAndBackToListButtonPartial.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit"
               class="btn btn-danger form-control"
               asp-route-id="@Model"
               value="Delete" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Udemy_Spice_MVC/Views/Shared/_DetailsAndBackToListButtonPartial.cshtml
@model int

<div class="row">
    <div class="col-6">
        <a class="btn btn-info form-control" 
           asp-action="Edit" 
           asp-route-Id="@Model">
            Edit
        </a>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Udemy_Spice_MVC/Views/Shared/_EditAndBackToListButtonPartial.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit"
               class="btn btn-info form-control"
               asp-route-id="@Model"
               value="Update" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Udemy_Spice_MVC/Views/Shared/_IndividualOrderDetails.cshtml
@model Udemy_Spice_MVC.Models.ViewModels.OrderDetailsViewModel
@using Udemy_Spice_MVC.Utility
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<form asp-action="OrderPickup" asp-controller="Order" asp-route-orderid="@Model.orderHeader.id" method="post">
    <div class="container row border ml-1 backgroundWhiteBorder10Padding" style="width:100%">
        <div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">
            <br />
            <input type="hidden" asp-for="orderHeader.id" />

            <div class="form-group row">
                <div class="col-3">
                    <label>Name</label>
                </div>
                <div class="col-9">
                    <input asp-for="orderHeader.pickup_name" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="orderHeader.app_user.Email"></label>
                </div>
                <div class="col-9">
                    <input asp-for="orderHeader.app_user.Email" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="orderHeader.app_user.PhoneNumber"></label>
                </div>
                <div class="col-9">
                    <input asp-for="orderHeader.app_user.PhoneNumber" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="orderHeader.order_total"></label>
                </div>
                <div class="col-9">
                    <input asp-for="orderHeader.order_total" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="orderHeader.pickup_time"></label>
                </div>
                <div class="col-9">
                    <input value="@Model.orderHeader.pickup_time.ToShortDateString() @Model.orderHeader.pickup_time.ToShortTimeString()" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="orderHeader.comments"></label>
                </div>
                <div class="col-9">
                    <input asp-for="orderHeader.comments" disabled class="form-control" />
                </div>
            </div>
        </div>



        <div class="col-lg-4 col-12">
            <h4 class="d-flex justify-content-between align-content-center mb-3">
                <span class="text-muted">Order ID: </span>
                <span class="badge badge-secondary badge-pill">@Model.orderHeader.id</span>
            </h4>
            <ul class="list-group mb-3">
                @foreach (var details in Model.orderDetails)
                {
                    <li class="list-group-item d-flex justify-content-between">
                        <div>
                            <h6 class="my-0">@details.name</h6>
                            <small class="text-muted">Quantity : @details.count</small>
                        </div>
                        <span class="text-muted">@string.Format("{0:N}", (details.price * details.count))</span>
                    </li>
                }
                @if (Model.orderHeader.coupon_code != null)
                {
                    <li class="list-group-item d-flex justify-content-between">
                        <div class="text-success">
                            <h6 class="my-0">Promo Code</h6>
                            <small>@Model.orderHeader.coupon_code</small>
                        </div>
                        <span class="text-success">@(Model.orderHeader.order_total_original - Model.orderHeader.order_total)</span>
                    </li>
                }
                <li class="list-group-item d-flex justify-content-between bg-light">
                    <span class="text-info"> Total (USD)</span>
                    <strong class="text-info">$@string.Format("{0:N}", Model.orderHeader.order_total)</strong>
                </li>

            </ul>
            @if (Model.orderHeader.status.Equals(SD.StatusReady) && (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.FrontDeskUser)))
            {
                <button type="submit" class="btn btn-success form-control"><i class="far fa-thumbs-up"></i> Confirm Pickup</button>
            }
            else
            {
                <button type="submit" disabled class=" btn-info form-control text-dark">@Model.orderHeader.status</button>
            }
        </div>

    </div>
</form>

Udemy_Spice_MVC/Views/Shared/_Layout.cshtml
@using Udemy_Spice_MVC.Utility
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Spice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/jquery-ui.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.11.0/jquery.timepicker.css" />

    <script src="https://kit.fontawesome.com/d57546c8d2.js" crossorigin="anonymous"></script>
</head>
<body class="search-background">
    <header>
        <nav id="nav-bar" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
                    <img src="~/images/mild.png" />
                    <img src="~/images/spicy.png" />
                    <img src="~/images/verySpicy.png" />
                    <label class="text-info" style="cursor:pointer">Spice</label>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(SD.ManagerUser))
                        {
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle"
                                   href="#" id="navbarDropdownMenuLink"
                                   role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Admin">Category</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">Sub-Category</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="MenuItem" asp-area="Admin">Menu Item</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Coupon" asp-area="Admin">Coupons</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="User" asp-area="Admin">Users</a>
                                </div>
                            </li>
                        }

                        @if (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.CustomerEndUser) || User.IsInRole(SD.FrontDeskUser) || User.IsInRole(SD.KitchenUser))
                        {
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Order
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                    <a asp-area="Customer" asp-controller="Order" asp-action="OrderHistory" class="dropdown-item">Order History</a>
                                    @if (User.IsInRole(SD.KitchenUser) || User.IsInRole(SD.ManagerUser))
                                    {
                                        <a class="dropdown-item" asp-action="ManageOrder" asp-controller="Order" asp-area="Customer">Manage Order</a>
                                    }
                                    @if (User.IsInRole(SD.FrontDeskUser) || User.IsInRole(SD.ManagerUser))
                                    {
                                        <a class="dropdown-item" asp-action="OrderPickup" asp-controller="Order" asp-area="Customer">Order Pickup</a>
                                    }
                                </div>

                            </li>
                        }

                        @if (HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssShoppingCartCount) != null &&
                           (@User.IsInRole(SD.CustomerEndUser) || @User.IsInRole(SD.ManagerUser)
                                 || @User.IsInRole(SD.FrontDeskUser) || @User.IsInRole(SD.KitchenUser)))
                        {
                            <li style="color:white">
                                <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssShoppingCartCount);
                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container render-body">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color: #343a40">
        <div class="container">
            &copy; 2021 - Udemy Course: Master ASP.NET MVC Core 3.1 <!-- - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> -->
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery-ui.js"></script>


    <script src="https://kit.fontawesome.com/d57546c8d2.js" crossorigin="anonymous"></script>
    <script src="https://cdn.tiny.cloud/1/y9c2xj9z7yee3uran7jmh8aymcwf8xcjnmzn9drlp3jmhkj4/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.js" integrity="sha512-17lKwKi7MLRVxOz4ttjSYkwp92tbZNNr2iFyEd22hSZpQr/OnPopmgH8ayN4kkSqHlqMmefHmQU43sjeJDWGKg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>
<!--
@section Script{
<script>
    $(function () {
        var navHeight = $("#nav-bar").height() + 'px'
        $(".render-body").css("margin-top", navHeight);
        document.write(navHeight)
    })
</script>
}-->

Udemy_Spice_MVC/Views/Shared/_OrderStatus.cshtml
@model Udemy_Spice_MVC.Models.ViewModels.OrderDetailsViewModel
@using Udemy_Spice_MVC.Utility

<div>
    @if (Model.orderHeader.status == SD.StatusSubmitted)
    {
        <img src="~/images/OrderPlaced.png" width="99%" style="border-radius:5px;border:1px solid #bbb9b9" />
    }
    @if (Model.orderHeader.status == SD.StatusInProcess)
    {
        <img src="~/images/InKitchen.png" width="99%" style="border-radius:5px;border:1px solid #bbb9b9" />
    }
    @if (Model.orderHeader.status == SD.StatusReady)
    {
        <img src="~/images/ReadyForPickup.png" width="99%" style="border-radius:5px;border:1px solid #bbb9b9" />
    }
    @if (Model.orderHeader.status == SD.StatusCompleted)
    {
        <img src="~/images/completed.png" width="99%" style="border-radius:5px;border:1px solid #bbb9b9" />
    }
</div>

Udemy_Spice_MVC/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Udemy_Spice_MVC/Views/Shared/_TableButtonsPartial.cshtml
@model int

<td style="width: 150px">
    <div class="btn-group" role="group">
        <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-edit"></i>
        </a>
        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

Udemy_Spice_MVC/Views/Shared/_ThumbnailAreaPartial.cshtml
@model IEnumerable<MenuItem>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@if (Model.Count() > 0)
{
    <div class="col-12 post @Model.FirstOrDefault().category.name.Replace(" ",string.Empty) menu-restaurant">
        <div class="row">
            <h3 class="text-success"> @Model.FirstOrDefault().category.name </h3>
        </div>

        @foreach (var item in Model)
        {
            <div class="border border-info rounded col-12" style="margin-bottom:10px; margin-top:10px; padding:10px">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <img src="@item.image" width="99%" style="border-radius:5px;border:1px solid #bbb9b9" />
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div class="row pr-3">
                            <div class="col-8">
                                <label class="text-primary" style="font-size:21px;color:maroon">@item.name</label>
                                @if (item.spicyness == "1")
                                {
                                    <img srcset="/images/mild.png" title="Mild" />
                                }
                                @if (item.spicyness == "2")
                                {
                                    <img srcset="/images/spicy.png" title="Spicy" />
                                }
                                @if (item.spicyness == "3")
                                {
                                    <img srcset="/images/veryspicy.png" title="Very Spicy" />
                                }
                            </div>
                            <div class="col-4 text-right" style="color:maroon">
                                <h4>$@item.price</h4>
                            </div>
                        </div>


                        <div class="row col-12 text-justify d-none d-md-block">
                            <p>@Html.Raw(item.description)</p>
                        </div>
                        <div class="col-md-3 col-sm-12 offset-md-9 text-center">
                            <a asp-action="Details" class="btn btn-success form-control" asp-route-id="@item.id">Details</a>
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="p-4"></div>
    </div>
}